spring:
  application:
    name: webbanhang
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          time_zone: UTC+7
      dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
springdoc:
  swagger-ui:
    path: swagger-ui.html
    operations-sorter: method